site_name: Suzieq
repo_url: https://github.com/netenglabs/suzieq
python:
  install:
    - requirements: docs/requirements.txt
theme:
  name: readthedocs
  navigation_depth: 3

nav:
  - Introduction: 'index.md'
  - Tutorials:
      - '10 things to do with Suzieq': tutorials/10things.md
      - 'How to think about verbs': tutorials/how_to_think_about_verbs.md
  - 'Getting Started': 'getting_started.md'
  - Architecture: architecture.md
  - Time: time.md
  - Tables: tables.md
  - Commands:
      - 'Command Introduction': commands/introduction.md
      - arpnd: 'commands/arpnd.md'
      - bgp: 'commands/bgp.md'
      - device: 'commands/device.md'
      - evpnVni: 'commands/evpnVni.md'
      - interface: 'commands/interface.md'
      - lldp: 'commands/lldp.md'
      - mac: 'commands/mac.md'
      - mlag: 'commands/mlag.md'
      - ospf: 'commands/ospf.md'
      - path: 'commands/path.md'
      - route: 'commands/route.md'
      - sqpoller: 'commands/sqpoller.md'
      - table: 'commands/table.md'
      - vlan: 'commands/vlan.md'
  - Verbs:
      - show: 'verbs/show.md'
      - unique: 'verbs/unique.md'
      - summarize: 'verbs/summarize.md'
  - API:
      - Sqobjects: 'api/sqobjects.md'
      - engine: 'api/engine.md'
      - poller: 'api/engine.md'
  - Service:
      - 'Interacting with devices': service/interacting_with_devices.md
      - JSONparsing: 'service/parsing.md'
      - textfsm: 'service/textfsm.md'

markdown_extensions:
  - mkautodoc


